name: CODEOWNERS Coverage Check
permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-codeowners:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v4
      - uses: mszostok/codeowners-validator@f555ba682ec613249e7e478a4e0bff3ba35dc79f # v0.7.2
        with:
          github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
          checks: "owners,duppatterns"
          experimental_checks: "notowned"
